
/*
 * NOTE:
 * THIS FILE IS AUTOGENERATED VIA OPTIONS.PY. DO NOT EDIT.
 */

#include <getopt.h>

enum {
    OPT_SIZE,
    OPT_HELP
};

typedef struct {
    int size;
    int size_cnt;
} opts_t;

static struct option long_options[] = {
    {"size", required_argument, 0, OPT_SIZE},
    {"help",       no_argument, 0, OPT_HELP},
    {0, 0, 0, 0}
};

#define OPTSTRING "s:"

static void printUsage ()
{
    printf("\t-s, --size number : size (Default: 262144)\n");
}

static void parseArgs(opts_t *opts, int argc, char **argv)
{
    int opt;
    while ((opt = getopt_long (argc, argv, OPTSTRING, long_options, NULL)) != -1)
        switch (opt) {
            case 's':
            case OPT_SIZE:
                opts->size = strtoul(optarg, NULL, 0);
                opts->size_cnt++;
                break;
            case OPT_HELP:
            default:
                printUsage();
                exit(0);
                break;
        }
}

opts_t opts = {
    .size = 262144,
};

